### ISSUE TITLE
wallaby.compilers is undefined

### ISSUE THREAD

**Issue by sheppy** [wallabyjs/public#100]
I'm trying to use the babel compiler as per the documentation, but wallaby.compilers is undefined.

I am using the latest wallaby-intellij-v1.0.11 and have tested using https://github.com/wallabyjs/wallaby-webpack-es7 and get the same error.

**Comment by ArtemGovorov** [comment]
Could you please share your wallaby.js config file?

**Comment by ArtemGovorov** [comment]
Also, what is your OS?

**Comment by sheppy** [comment]
OS: Windows 8.1 Pro
IDE: WebStorm 10.02

Using the webpack es7 example, so the config is the same as here: https://github.com/wallabyjs/wallaby-webpack-es7/blob/master/wallaby.js

**Comment by sheppy** [comment]
If it helps, when I output wallaby I do not get most of the parameters the document says should be there... I just get

```
{
   localProjectDir: 'C:/www/wallaby-webpack-es7'
}
```

Where I would expect to get localProjectDir, projectCacheDir, compilers, defaults

**Comment by ArtemGovorov** [comment]
Did you already install wallaby.js a while ago and started using again just today? If that's the case, please  activate it with the early adopter license that I have sent out in the most recent newsletter (at the end of the email). Then try restarting WebStorm and start wallaby.js, it should update wallaby core and the issue should be fixed.

If it's not the case, please add `debug: true` to the root of wallaby configuration object and run it. Open the "Wallaby Console" tab and one of the first lines will be a path to wallaby file cache. Open the folder, go 2 levels up, then to wallaby folder and check what version is in package.json (second property).

**Comment by sheppy** [comment]
I had indeed used a previous version 1.0.5. I have activated the early adopter licence - restarted, even uninstalled and re-installed the plugin and still get the same issue.

Adding debug: true to my config does not add any additional logging to the console.

However I did manage to track down what I think is the wallaby folder, the version in package.json is "version": "1.0.39".

I decided to uninstall again (and closed webstorm) and the wallaby folder was still there, tried deleting manually but was still open from a PhantomJS process. After killing the process, deleting the folder and re-installing everything is now working fine.

So not sure what the exact issue was - but seems phantom was still running that was causing issues - thanks for the help in tracking it down.
