### ISSUE TITLE
Unable to start wallaby within Sublime 3

### ISSUE THREAD

**Issue by wdmartins** [wallabyjs/public#1556]
### Issue description or question
I am trying to run the simple calculator example from the Sublime Text tutorial. Everything fine till I try to start wallaby. At that point nothing happens. Setting the debug option I can see the following on the console:

[Debug]: 'Starting wallaby.js plugin'
[Debug]: 'Restarting wallaby.js plugin'
[Debug]: 'Restart stop: 3'
[Debug]: 'stop print content to testsView'
[Debug]: 'Wallaby.js stopped'
[Debug]: 'Project opened'
[Debug]: 'Plugin path: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby'
[Debug]: 'Config path: /home/wosmodev/repos/calculator-sample/wallaby.js'
[Debug]: 'Cache path: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby/projects/3f8608304815110a'
[Debug]: 'Core folder path: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby/wallaby'
[Debug]: 'Phantom folder path: /home/wosmodev/.config/sublime-text-3'
[Debug]: 'Platform: linux x32'
[Debug]: 'Version file: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby/wallaby/package.json'
[Debug]: 'Version file: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby/wallaby/package.json'
[Debug]: 'Starting checking for updates'
[Debug]: 'Downloading and parsing config JSON'
[Debug]: 'Current core version: 0.0.0'
[Debug]: 'Last core version: 1.0.568'
[Debug]: 'Need to update Phantom'
[Debug]: 'Need to update phantom to version:2.1.1'
[Debug]: 'Download: https://s3.amazonaws.com/wallaby-downloads/phantom/phantomjs-2.1.1-i686.tar.bz2'
[Debug]: 'Issue with plugin start: HTTP Error 404: Not Found'

The phantomjs download url seems to be incorrectly constructed as that file does not exist. So I tried installing phantomjs 2.1.1 myself and put the phantomjs file inside ~/.config/sublime-text-3/Packages/Wallaby/phantomjs_v2.1.1
That did not hep as trying to start wallaby after that shows exactly the same output on the console.

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      'style/calculator.css',
      {pattern: 'lib/jquery.js', instrument: false},
      'src/*.js',
      'test/helper/template.js'
    ],
    tests: [
      'test/*Spec.js'
    ],
    debug: true
  };
};
```

### Code editor or IDE name and version
Sublime Text 3 Build 3143

### OS name and version

Linux
uname -a
Linux linux 3.4.6-2.10-default #1 SMP Thu Jul 26 09:36:26 UTC 2012 (641c197) i686 i686 i386 GNU/Linux

##### NodeJs Version
v4.8.5

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in wallaby package v1.0.40 (it may take ~1 hour before the update is available in the package control repo).

**Comment by wdmartins** [comment]
Hi @ArtemGovorov,
I reinstall wallaby (v.1.0.40) and I can see the phantom download url is now correctly formatted and if I try manually I can download it however, when starting wallaby from sublime this is shown in the console and nothing else happens:

[Debug]: {2: <Wallaby.wallaby.Wallaby object at 0xb39f8f6c>}
[Debug]: 'Windows: [2, 3]'
[Debug]: 'Projects: dict_keys([2])'
[Debug]: 'closedProjects: []'
[Debug]: 'Starting wallaby.js plugin'
[Debug]: 'Project opened'
[Debug]: 'Plugin path: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby'
[Debug]: 'Config path: /home/wosmodev/repos/calculator-sample/wallaby.js'
[Debug]: 'Cache path: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby/projects/3f8608304815110a'
[Debug]: 'Core folder path: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby/wallaby'
[Debug]: 'Phantom folder path: /home/wosmodev/.config/sublime-text-3'
[Debug]: 'Platform: linux x32'
[Debug]: 'Version file: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby/wallaby/package.json'
[Debug]: 'Version file: /home/wosmodev/.config/sublime-text-3/Packages/Wallaby/wallaby/package.json'
[Debug]: 'Starting checking for updates'
[Debug]: 'Downloading and parsing config JSON'
[Debug]: 'Current core version: 0.0.0'
[Debug]: 'Last core version: 1.0.568'
[Debug]: 'Need to update Phantom'
[Debug]: 'Need to update phantom to version:2.1.1'
[Debug]: 'Download: https://s3.amazonaws.com/wallaby-downloads/phantom/phantomjs-2.1.1-linux-i686.tar.bz2'
[Debug]: 'Issue with plugin start: HTTP Error 400: Bad Request'
[Debug]: {2: <Wallaby.wallaby.Wallaby object at 0xb39f8f6c>,
 3: <Wallaby.wallaby.Wallaby object at 0xb3982d4c>}
[Debug]: 'Windows: [2, 3]'
[Debug]: 'Projects: dict_keys([2, 3])'
[Debug]: 'closedProjects: []'

Thanks!

**Comment by ArtemGovorov** [comment]
@wdmartins Hmm, interesting. We have added another fix (even though we can't reproduce the issue locally in our environment) and published in wallaby package v1.0.41 (it may take ~1 hour before the update is available in the package control repo). Please try it and let us know how it goes.

**Comment by wdmartins** [comment]
@ArtemGovorov unfortunately the issue remains. Is there any specific proxy settings for Wallaby?
Is the any other information, logs I can provide?

**Comment by ArtemGovorov** [comment]
Are you behind some (corporate) proxy?

Try this:
- download the required PhantomJs version (like you have already done),
- unzip it to `~/.config/sublime-text-3/phantomjs_v2.1.1`, so that it looks like this:

<img width="177" alt="screen shot 2018-03-17 at 7 48 21 am" src="https://user-images.githubusercontent.com/979966/37546244-9bc05c54-29b7-11e8-8779-92686ea37f1d.png">

- (re)start the editor and start Wallaby.
