### ISSUE TITLE
Error "Error: Your test suite must contain at least one test." doesn't getting resolved after file deletion

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2183]
### Issue description or question

1. Start Wallaby
2. Create an empty test file - the error "Error: Your test suite must contain at least one test." would be raised
3. Delete created empty test file

EB: The error should disappear
CB: The error persists until tests rerun or Wallaby restart

Note: if the file contains, for example, a fallen test, after been deleted the Wallaby is rerunning and the error disappears, just as expected. So the issue is specifically with deletion of an empty file

### Wallaby.js configuration file

Autoconfig with Jest 24.8

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

Windows 10 Pro

**Comment by smcenlly** [comment]
We fixed an issue yesterday that caused this problem, #2179. I can't reproduce using the latest version of our WebStorm plugin, with the latest version of Wallaby core.

Could you please [download](https://download.wallabyjs.com/intellij) and install the latest version of Wallaby for WebStorm.

After that, if you're still experiencing the problem, you may need to [force wallaby core to update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

If it's still not working after both of these steps, let us know and we will re-open this issue.

**Comment by Alexsey** [comment]
@smcenlly hi, the link to download that you have posted is leading to the old v1.0.136. The files inside are two month old

**Comment by smcenlly** [comment]
@Alexsey - the download appears to be correct for me. We update the editor integration and Wallaby runtime separately. The last release of the editor integration was July 25th 2019. That should be the date you see (that's the date that I see in my archive). Once you install the editor plugin, it will download the runtime, which is usually updated every 2-3 days.

Can you please let us know what date you're seeing in the archive and what the name of the downloaded file was?

**Comment by Alexsey** [comment]
It was June 25th, 2019, just as you mentioned. But in this case, the error has not been resolved. Let me give you more detailed STR:
1. In `/test` folder, create `file.test.js` - the error ".\test\file.test.js: Error: Your test suite must contain at least one test." would be raised
2. Delete `file.test.js` with `Soft delete` flag turned off

EB: the error should disappear
CD: the error is still in the `Failing Tests` tab

The error would disappear if anything triggered tests recalculation

**Comment by ArtemGovorov** [comment]
The issue is now fixed and the fix is published [the latest Wallaby core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
