### ISSUE TITLE
Lot of problems with Webstorm 2020.1

### ISSUE THREAD

**Issue by vjau** [wallabyjs/public#2392]
### Issue description or question

Since update of Webstorm  to 2020.1, Wallaby doesn't work correctly.

I have done the manual update to 1.0.171
I am using Jest 25.2.7, Babel Core 7.9, Typescript 3.8.3.
I'm on Ubuntu 18.04
Wallaby uses automatic configuration.
I cannot give you the diagnostic report since when i try the command it says `Failed to copy to clipboard. write EPIPE`
Everytime there is the slightest error in my tests or in my code, the "failing tests" windows shows 
`Test run failure: ` and that's all.

Sometimes i get a java stacktrace

```java
java.lang.NullPointerException
	at com.wallaby.javascript.execution.n.a(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

In the wallaby console, i get this:
```js
console.log: Jest: FAIL src/Validators/tests/isCompletePDT.test.ts

console.log: Jest:   ● Test suite failed to run

    TypeError: src/Validators/tests/isCompletePDT.test.ts: Emit skipped for language service
      at compileFn (node_modules/ts-jest/dist/compiler/language-service.js:101:23)
      at Object.compile (node_modules/ts-jest/dist/compiler/instance.js:90:25)
      at TsJestTransformer.process (node_modules/ts-jest/dist/ts-jest-transformer.js:94:41)
      at TsJestTransformer.e.process (../../.cache/JetBrains/WebStorm2020.1/wallaby/wallaby/runners/node/jest@24.8.0/initializer.js:14:18547)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:446:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:525:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:563:25)


Runtime error: undefined
```

**Comment by vjau** [comment]
The actual problem seems related to ts-jest, but yesterday when i was trying with the typescript preset for babel, i also got problems.
When the tests are green, everything displays correctly, but when there is the slightes error (syntax or other), wallaby goes berserk and doesn't understand what jest is saying.

**Comment by ArtemGovorov** [comment]
Can you please share your
- Jest config,
- tsconfig.json,
- ts-jest version.

Looks like the issue is related to `ts-jest`.

> but yesterday when i was trying with the typescript preset for babel, i also got problems.

What were the error messages/issues?

> but when there is the slightes error (syntax or other), wallaby goes berserk and doesn't understand what jest is saying.

Are you sure the issue is reproducible for non syntactic error? Ie. test expectation failure are also misreported?

**Comment by vjau** [comment]
I'm struggling with Typescript optionnal chaining Operator.
Since my project is an electron project with webpack, i have a babel.config.js like this

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          electron: '8.1.1',
        },
      },
    ],
    '@babel/preset-typescript'
  ],
};
```

But when doing this with Jest using , it complains that it doesn't understand the optional chaining operator (since it is supported natively by electron, but not by node ?).

So i looked online and found out i could use ts-jest, but now on every typescript error i get no emit.


So i added a ts-jest config like this :

```js
module.exports = {
  globals: {
    'ts-jest': {
      isolatedModules: true,
      babelConfig: {
        targets :{
          ie : 11
        }
      }
    }
  }
```
IsolatedModules prevents ts-jest from checking typing. 
Trying to force ie11 so that jest is happy. But then the optional chaining problem came back.

Ts-jest version is 25.3.1

Tsconfig.json
```
{
  "extends": "./node_modules/electron-webpack/tsconfig-base.json",
  "compilerOptions": {
    "target": "es2019",
    "module": "esNext",
    "lib": [
      "esnext",
      "dom"
    ],
    "allowJs": true,
    "checkJs": false,

    "jsx": "react",
    /* Strict Type-Checking Options */
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    /* Additional Checks */
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": false,
    "noFallthroughCasesInSwitch": false,
    /* Module Resolution Options */
    "baseUrl": ".",
    "paths": {
      /* Support absolute /imports/* with a leading '/' */
      "/*": [
        "*"
      ]
    },
    "outDir": "./dist/",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "types": [
      "node", "jest"
    ],
    "esModuleInterop": true,
    "preserveSymlinks": true,
    "sourceMap": true
  },
  "exclude": [
    "./node_modules/**"
  ]
}
```

> Are you sure the issue is reproducible for non syntactic error? Ie. test expectation failures are also misreported?

No, i'm not sure about this, but Wallaby has became very finicky during the update from Webstorm 2019 to 2020, the optional chaining problem is in a test that has been there for  more than a month (probably the problem was already there but failed silently).

**Comment by vjau** [comment]
Ok, when writing `foo = 15` in a test (where there should be an array), wallaby pass out.
Now, when replacing by `foo = [15]` wallaby wakes up and the test is green. So this is NOT only syntax related.

**Comment by ArtemGovorov** [comment]
Can you try to add

```
throw new Error('test');
```

does Wallaby correctly show the error in this case?

**Comment by vjau** [comment]
Yes, i get "Error: test" on the same line. 
But the reports says "1 failing test, 0 passing". I have more than one test in my project.

**Comment by vjau** [comment]
When removing the throw new Error, the test becomes green althought there is still the typescript type error (part not tested in this test). When correcting the type error, everything is happy. But still saying that i have only one test. 
When reloading wallaby (no other change made), i get the dreaded "Test run failure:"

**Comment by ArtemGovorov** [comment]
Ok, thanks, the error seems to be related to ts-jest only. We'll investigate `ts-jest` integration.

Does running Jest CLI from the project's root via `npx jest` work?

> So i added a ts-jest config like this :
```
module.exports = {
  globals: {
    'ts-jest': {
      isolatedModules: true,
      babelConfig: {
        targets :{
          ie : 11
        }
      }
    }
  }
```

This is not your full Jest config, is it? There supposed to be either `preset: 'ts-jest',`, or Jest `transform` setting configured.

> But the reports says "1 failing test, 0 passing". I have more than one test in my project.

If you have added the line in your file outside of any `it`/`test`, then it is expected, because the global error stops Wallaby from executing other tests. If you put the line into one of your tests, it should work as you expect.

**Comment by vjau** [comment]
> Ok, thanks, the error seems to be related to ts-jest only. We'll investigate ts-jest integration.

I'm not sure about this.
When trying jest without ts-jest (by removing all configuration in jest.config.js), trying jest on the command line works, except for the tests using code with optionnal chaining.

```
Test Suites: 1 failed, 5 passed, 6 total
Tests:       24 passed, 24 total
Snapshots:   0 total
Time:        4.164s
Ran all test suites.
error Command failed with exit code 1.
```

But still, on the wallaby front :

Failing test window
```
Test run failure: 
```

Wallaby console:
```js
wallaby.js started
core v1.0.876
console.log: Jest: PASS src/processing/tests/actesToCotations.test.ts

console.log: Jest:   ● Console

    console.log ../../.cache/JetBrains/WebStorm2020.1/wallaby/wallaby/server.js:24
      floastString 107.5
    console.log ../../.cache/JetBrains/WebStorm2020.1/wallaby/wallaby/server.js:24
      floastString 90


console.log: Jest: PASS src/Validators/tests/isCompletePDT.test.ts

console.log: Jest: FAIL src/utils/tests/ssNumbers.test.ts

console.log: Jest:   ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/vincent/dev/autopec/src/utils/ssNumbers.ts:72
                return $_$w(37, 58, $_$c), rules[idx]?.includes(str) ? ($_$w(37, 59, $_$c), str) : ($_$w(37, 60, $_$c), '');
                                                      ^

    SyntaxError: Unexpected token '.'
      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1085:14)
      at Object.<anonymous> (src/utils/tests/ssNumbers.test.ts:3:38)


Runtime error: undefined
console.log: Jest: PASS src/processing/tests/textToActes.test.ts

console.log: Jest: PASS src/processing/tests/actesToNarrowedActes.test.ts

console.log: Jest: PASS src/utils/tests/formatDDNForStoring.test.ts
```

**Comment by ArtemGovorov** [comment]
>  trying jest on the command line works, except for the tests using code with optionnal chaining.

Ok, thanks, I wasn't sure if optional chaining was Wallaby related issue or Jest setup related. Let's address one issue at a time.

So Jest without Wallaby is failing for one spec. Wallaby seems to also be failing for the same spec, but prints no error details: `Test run failure: `.

We have just fixed the reporting issue. Please update to [the latest Wallaby core v.0.877](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and wallaby now should report the `Test run failure` correctly. 

Back to the issue with `ts-jest`, if you put your Jest config for `ts-jest` back and run Jest from command line, are all of your tests passing? If so, please share the full Jest config that works, we'll  try to reproduce the issue with Wallaby.

**Comment by vjau** [comment]
> We have just fixed the reporting issue. Please update to the latest Wallaby core v.0.877 and wallaby now should report the Test run failure correctly.

This seems to improve the situation, thanks. 
However, there is a new problem.

```js
console.log: Jest: FAIL src/utils/tests/ssNumbers.test.ts

console.log: Jest:   ● Test suite failed to run

    TypeError: Cannot set property '0' of undefined
      at a.statement (../../.cache/JetBrains/WebStorm2020.1/wallaby/wallaby/server.js:24:3879)
      at l.$_$w.e.$_$w.e.$_$w_ (../../.cache/JetBrains/WebStorm2020.1/wallaby/wallaby/server.js:25:8769)
      at Object.<anonymous> (src/utils/ssNumbers.ts:76:1)
      at Object.<anonymous> (src/utils/tests/ssNumbers.test.ts:3:38)


Runtime error: TypeError: Cannot set property '0' of undefined
    at Object.<anonymous> (./src/utils/ssNumbers.ts:76:1)
    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1056:24)
    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:684:12)
    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:542:10)
    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:705:21)
    at Object.<anonymous> (./src/utils/tests/ssNumbers.test.ts:3:38)
    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1056:24)
    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:684:12)
    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:542:10)
    at jasmine2 (./node_modules/jest-jasmine2/build/index.js:201:11)
    at runTestInternal (./node_modules/jest-runner/build/runTest.js:414:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runTest (./node_modules/jest-runner/build/runTest.js:488:34)
```

It still the same code which was causing problems with optional chaining.
I have fixed the problem with jest by using only @babel/preset-env and @babel/preset-typescript and targeting an older version of electron.

The problem is that the code is valid, and running jest from the command line gives me only green tests. 

I guess it's cache related with wallaby but doesn't know how to invalidate the cache.

**Comment by ArtemGovorov** [comment]
> I guess it's cache related with wallaby but doesn't know how to invalidate the cache

Try running `jest --clearCache` in your repo's root.

**Comment by ArtemGovorov** [comment]
> I'm on Ubuntu 18.04
> I cannot give you the diagnostic report since when i try the command it says Failed to copy to clipboard. write EPIPE


Can you check and see if `xclip` is installed? Our copy module uses that command line utility to gain access to the system's clipboard.

**Comment by ArtemGovorov** [comment]
> java.lang.NullPointerException

We have also published Wallaby plugin v1.0172 where we have tried to fix the reason for the exception. After updating to the latest version of the plugin, please let us know if you see the `NullPointerException` in your WebStorm again.

**Comment by smcenlly** [comment]
Closing this issue. Please let us know if you're still having any problems and we can re-open or else move your problem to a new issue.
