### ISSUE TITLE
Angular/Karma/Jasmine configuration for remote containers

### ISSUE THREAD

**Issue by snerdini** [wallabyjs/public#3093]
### Issue description or question

I'm working on containerizing our development environment (Angular/Karma/Jasmine) using remote containers in VS Code, but I'm having some issues with Wallaby. I've verified that Chrome is installed and runs (using X410 for remote display), but for some reason, the Wallaby sandbox cannot connect with Chrome. I read that Wallaby supports remote containers (and I've gotten Wallaby to initialize successfully using Jest) - any idea what the problem is here? 

I've published a sample repo here: https://github.com/snerdini/wallaby-dev-containers

### Wallaby diagnostics report

```
{
  editorVersion: '1.72.1',
  pluginVersion: '1.0.348',
  editorType: 'VSCode',
  osVersion: 'linux 5.10.102.1-microsoft-standard-WSL2',
  nodeVersion: 'v14.20.1',
  coreVersion: '1.0.1334',
  checksum: 'N2ZmNGVmNDYzYThkNmIyNThjZDA0YzM2ZTFmNzgyZTMsMTY3NzE5NjgwMDAwMCww',
  config: {
    trace: true,
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            'wallaby-dev-containers': {
              projectType: 'application',
              schematics: { '@schematics/angular:component': { style: 'scss' }, '@schematics/angular:application': { strict: true } },
              root: '',
              sourceRoot: 'src',
              prefix: 'app',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    outputPath: 'dist/wallaby-dev-containers',
                    index: 'src/index.html',
                    main: 'src/main.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.app.json',
                    inlineStyleLanguage: 'scss',
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [ 'src/styles.scss' ],
                    scripts: []
                  },
                  configurations: {
                    production: {
                      budgets: [ { type: 'initial', maximumWarning: '500kb', maximumError: '1mb' }, { type: 'anyComponentStyle', maximumWarning: '2kb', maximumError: '4kb' } ],
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],
                      outputHashing: 'all'
                    },
                    development: { buildOptimizer: false, optimization: false, vendorChunk: true, extractLicenses: false, sourceMap: true, namedChunks: true }
                  },
                  defaultConfiguration: 'production'
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  configurations: { production: { browserTarget: 'wallaby-dev-containers:build:production' }, development: { browserTarget: 'wallaby-dev-containers:build:development' } },
                  defaultConfiguration: 'development'
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'wallaby-dev-containers:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    main: 'src/test.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.spec.json',
                    karmaConfig: 'karma.conf.js',
                    inlineStyleLanguage: 'scss',
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [ 'src/styles.scss' ],
                    scripts: []
                  }
                }
              }
            }
          },
          defaultProject: 'wallaby-dev-containers'
        },
        main: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
          '\n' +
          "import 'zone.js/testing';\n" +
          "import { getTestBed } from '@angular/core/testing';\n" +
          'import {\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting\n' +
          "} from '@angular/platform-browser-dynamic/testing';\n" +
          '\n' +
          'declare const require: {\n' +
          '  context(path: string, deep?: boolean, filter?: RegExp): {\n' +
          '    keys(): string[];\n' +
          '    <T>(id: string): T;\n' +
          '  };\n' +
          '};\n' +
          '\n' +
          '// First, initialize the Angular testing environment.\n' +
          'getTestBed().initTestEnvironment(\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting(),\n' +
          '  { teardown: { destroyAfterEach: true }},\n' +
          ');\n' +
          '\n' +
          '// Then we find all the tests.\n' +
          '\n' +
          '// And load the modules.\n' +
          '\n'
      }
    },
    testFramework: { version: 'jasmine@3.10.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/polyfills.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/test.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/main.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/index.html', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/test.base.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 2 },
      { pattern: 'src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 3 }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 4 } ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#1313788472'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '~12.2.0',
      '@angular/common': '~12.2.0',
      '@angular/compiler': '~12.2.0',
      '@angular/core': '~12.2.0',
      '@angular/forms': '~12.2.0',
      '@angular/platform-browser': '~12.2.0',
      '@angular/platform-browser-dynamic': '~12.2.0',
      '@angular/router': '~12.2.0',
      rxjs: '~6.6.0',
      tslib: '^2.3.0',
      'zone.js': '~0.11.4'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '~12.2.5',
      '@angular/cli': '~12.2.5',
      '@angular/compiler-cli': '~12.2.0',
      '@types/jasmine': '~3.8.0',
      '@types/node': '^12.11.1',
      'jasmine-core': '~3.8.0',
      karma: '~6.3.0',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage': '~2.0.3',
      'karma-jasmine': '~4.0.0',
      'karma-jasmine-html-reporter': '~1.7.0',
      typescript: '~4.3.5'
    }
  },
  fs: { numberOfFiles: 9 },
  debug: [
    '2022-10-12T15:48:54.810Z config Attempting automatic configuration for angular\n',
    '2022-10-12T15:48:54.816Z angular/cli config Detected Angular CLI.\n',
    '2022-10-12T15:48:54.818Z angular/cli config Angular currentDirPath: "<rootDir>", workspaceDirPath: "<rootDir>"\n',
    '2022-10-12T15:48:57.280Z angular/cli karma project config Using virtual <rootDir>/src/test.ts.\n',
    '2022-10-12T15:48:57.321Z config Finished attempting automatic configuration for angular (2512ms)\n',
    '2022-10-12T15:48:57.323Z project Wallaby Node version: v14.20.1\n',
    '2022-10-12T15:48:57.324Z project Wallaby config: <rootDir>/auto.detect\n',
    '2022-10-12T15:48:57.331Z fs File system starting\n',
    '2022-10-12T15:48:57.367Z fs File system scan completed\n',
    '2022-10-12T15:48:57.374Z project File cache: <homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.348/projects/ff218669bfa697f9\n',
    '2022-10-12T15:48:57.437Z uiService Listening port 51235\n',
    '2022-10-12T15:48:57.442Z project package.json file change detected, invalidating local cache\n',
    '2022-10-12T15:48:57.534Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2022-10-12T15:48:57.535Z workers Starting run worker instance #0\n',
    '2022-10-12T15:48:57.535Z workers Starting run worker instance #1\n',
    '2022-10-12T15:48:57.535Z workers Starting run worker instance #2\n',
    '2022-10-12T15:48:57.535Z workers Starting run worker instance #3\n',
    '2022-10-12T15:48:57.535Z workers Starting run worker instance #4\n',
    '2022-10-12T15:48:57.535Z workers Starting run worker instance #5\n',
    '2022-10-12T15:48:57.537Z workers Web server is listening at 40165\n',
    '2022-10-12T15:48:57.551Z project Stopping process pool\n',
    '2022-10-12T15:48:57.551Z project File cache is up-to-date, starting full test run\n',
    '2022-10-12T15:48:57.554Z project Running postprocessor\n',
    '2022-10-12T15:48:57.557Z postprocessor Processing started.\n',
    '2022-10-12T15:48:57.557Z postprocessor Initializing.\n',
    '2022-10-12T15:48:57.557Z postprocessor Initializing entry.\n',
    '2022-10-12T15:48:57.557Z postprocessor Sanitizing configuration.\n',
    '2022-10-12T15:48:57.557Z postprocessor Adjusting configuration.\n',
    '2022-10-12T15:48:57.559Z postprocessor Creating compiler.\n',
    '2022-10-12T15:48:57.698Z postprocessor Customizing compiler.\n',
    '2022-10-12T15:48:57.699Z postprocessor Compilation started.\n',
    '2022-10-12T15:49:04.236Z postprocessor Compilation finished.\n',
    '2022-10-12T15:49:04.680Z postprocessor Emitting 340 files.\n',
    '2022-10-12T15:49:04.686Z postprocessor Processing finished.\n',
    '2022-10-12T15:49:04.750Z project Postprocessor execution finished\n',
    '2022-10-12T15:49:04.750Z project Test run started; run priority: 3\n',
    '2022-10-12T15:49:04.753Z project Running all tests\n',
    '2022-10-12T15:49:04.762Z workers Starting test run, priority: 3\n',
    '2022-10-12T15:49:04.762Z chromeRunner Starting sandbox [worker #0, session #5i3o3]\n',
    '2022-10-12T15:49:26.759Z workers Started run worker instance (immediate) #0\n',
    '2022-10-12T15:49:26.759Z workers Started run worker instance (immediate) #1\n',
    '2022-10-12T15:49:26.759Z workers Started run worker instance (immediate) #2\n',
    '2022-10-12T15:49:26.759Z workers Started run worker instance (immediate) #3\n',
    '2022-10-12T15:49:26.759Z workers Started run worker instance (immediate) #4\n',
    '2022-10-12T15:49:26.759Z workers Started run worker instance (immediate) #5\n',
    '2022-10-12T15:49:26.759Z chromeRunner Preparing sandbox [worker #0, session #5i3o3]\n',
    '2022-10-12T15:49:26.760Z browserRunner Total files to load in sandbox: 5\n',
    '2022-10-12T15:49:26.762Z browserRunner Sandbox is generated [worker #0, session #5i3o3]: http://localhost:40165/wallaby_sandbox0.html\n',
    '2022-10-12T15:49:26.762Z chromeRunner Prepared sandbox [worker #0, session #5i3o3]\n',
    '2022-10-12T15:49:26.762Z workers [worker #0, session #5i3o3] Running tests in sandbox\n',
    "2022-10-12T15:49:26.764Z chromeRunner Failed to evaluate code on Chrome Tab: Cannot read property 'Runtime' of undefined\n",
    '2022-10-12T15:49:27.265Z workers [5i3o3] Sandbox is not responsive, recycling worker instance\n',
    '2022-10-12T15:49:27.265Z workers Recyling run worker instance #0\n',
    '2022-10-12T15:49:27.266Z project Test run finished\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for the sample repo. We set your repo up on a Linux machine with docker containers, and everything worked for us without us needing to do anything special.

<img width="1705" alt="image" src="https://user-images.githubusercontent.com/2074089/195486353-32ce31dd-804c-49e3-9cdf-6787d97286ff.png">

Do your tests run when you use the CLI?

I believe that your docker instance is connect to your local browser instance when running browser-based tests so perhaps you have a firewall issue? Try turning off your firewall and virus scanner as that may help.

Could you also please try another machine? You may have some environmental issue.

**Comment by snerdini** [comment]
Sorry, forgot to mention that I'm running Windows 10 with a WSL2 backend - I've tested on another machine that is Windows 11, also with WSL2 - both have the same issue. I can run `ng test` successfully, but when starting Wallaby, I only see 4 forwarded ports, whereas when I run `ng test` from a terminal, 6 ports are open. I've attached the differences between the two.

**Comment by smcenlly** [comment]
Did you try turning off your firewall and virus scanner on both machines?

**Comment by snerdini** [comment]
Unfortunately, I can only turn firewall/AV off on one of the two machines - the other is controlled by group policy. Let me try on a Linux machine to see if I can get it to successfully run there. Our team loves Wallaby and wants to migrate to a containerized development environment, but this is a blocker for us at the moment.

Was the `ng test` process on port 9876 started by Wallaby on your machine? I'm not even getting that for some reason - as you can see above, it works fine when executing `ng test` from within the container manually, but does not execute during the Wallaby startup process.

Anything else I could try? I'll keep digging in the meantime to see if I can turn anything up.

**Comment by smcenlly** [comment]
We think we have found the cause of your problem. Wallaby checks whether you're running in a remote instance of VS Code for WSL and the WSL check can fail if your running from a Windows machine and using an operating system with a realse by `microsoft`.

We've updated this check to also ensure that the container is a not a docker instance, which should fix your problem if your tests are passing from the CLI with `ng test`.

**Comment by snerdini** [comment]
Thanks, Simon! I can see that Wallaby is now running successfully in the sample repo. There still seem to be some issues, however: 

### General Failures in Test Runs
`​[Info]​ 2022-11-01T14:18:11.905Z middleware Serving /jasmine@2.1.3/starter.js from disk`
We are currently using Jasmine 3.x - does it matter that the versions don't match? 

When I get failures, I'm seeing errors like this: 

`​​[Error] Chrome runner error: Error: Missing tracer start subscription​​`

I can't tell if there is something wrong with our tests, but they were passing in WSL (outside of a container) previously (and they're passing with `ng test`).

### Licensing Issues
Also, if I run more than one container at a time and attempt to run Wallaby, I get the following message:

`Wallaby.js is stopped because your license is being used elsewhere on the network by {{container_id}} (x.x.x.x). Only one active computer at the same time may use the license. If you would like to purchase an additional license, please visit our website. If you have already purchased the license, please activate it. `

### WSL Functionality
It appears that the fix for dev containers may have broken general WSL compatibility - if we attempt to run Wallaby in the same project strictly in WSL (not in a container) we now get the this error:

```
​[Error] connect ECONNREFUSED 127.0.0.1:46693​​
​​[Error]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)​​
```

Let me know if you need clarification on any of the above issues. Thanks!

**Comment by smcenlly** [comment]
Please see responses below:

> ### General Failures in Test Runs
> `​[Info]​ 2022-11-01T14:18:11.905Z middleware Serving /jasmine@2.1.3/starter.js from disk`
> We are currently using Jasmine 3.x - does it matter that the versions don't match? 

The `@2.1.3` is Wallaby's internal Jasmine integration version for starting Jasmine; you can safely ignore this version.

> When I get failures, I'm seeing errors like this: 
> 
> `​​[Error] Chrome runner error: Error: Missing tracer start subscription​​`
> 
> I can't tell if there is something wrong with our tests, but they were passing in WSL (outside of a container) previously (and they're passing with `ng test`).

What kind of failures cause this error? Is it happening often? Can you please share your [diagnostics report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report) after getting this error?
 
> ### Licensing Issues
> Also, if I run more than one container at a time and attempt to run Wallaby, I get the following message:
> 
> `Wallaby.js is stopped because your license is being used elsewhere on the network by {{container_id}} (x.x.x.x). Only one active computer at the same time may use the license. If you would like to purchase an additional license, please visit our website. If you have already purchased the license, please activate it. `

This can happen for some machines using containers / WSL depending on how your network stack is configured. Please email hello@wallabyjs.com with your existing license key, we'll be able to help you from there.

> ### WSL Functionality
> It appears that the fix for dev containers may have broken general WSL compatibility - if we attempt to run Wallaby in the same project strictly in WSL (not in a container) we now get the this error:
> 
> ```
> ​[Error] connect ECONNREFUSED 127.0.0.1:46693​​
> ​​[Error]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)​​
> ```
> 
> Let me know if you need clarification on any of the above issues. Thanks!

You're right, we had inadvertently broken this. It is fixed in Wallaby core `v1.0.1342`.

**Comment by smcenlly** [comment]
Do you still have outstanding issues? If not, I will close this issue.

**Comment by snerdini** [comment]
WSL is working for us again, but I'm still having issues running in a container. I'll try to do some troubleshooting later this week and see if I can get you a diagnostics report.

**Comment by smcenlly** [comment]
Let's close this issue. If you have further issues, please open a new issue and we can take it from there.
