### ISSUE TITLE
Failed to parse '/allFiles.jsx' with es7 stage-0 syntax (static proptypes)

### ISSUE THREAD

**Issue by rpmonteiro** [wallabyjs/public#647]
### Issue description or question
Failed to parse files that contain ``static proptypes = {...}`` which is a es7 stage-0 feature.
`` SyntaxError: Unexpected token (11:19) ``

Wallaby throws 2 errors of the kind, and then stops. It seems to randomly load the files, so the files that error are generally different most of the times. I have dozens of files that use ``static proptypes = {...}``

ObiWan @ArtemGovorov , help this team get through this ordeal so we can buy our licenses and live a happy life full of tests.

### .babelrc configuration file

```json
{
  "presets": ["es2015", "react", "babel-preset-stage-0"],
  "plugins": ["transform-class-properties"],
  "env": {
    "production": {
      "plugins": [
        "transform-react-constant-elements",
        "transform-react-inline-elements",
        "transform-class-properties"
      ]
    }
  }
}

```

### Wallaby.js configuration file

```javascript
var babel = require('babel-core');

module.exports = function (wallaby) {
  return {
    files: [
      'src-cls/**/*.js*',
      {pattern: 'src-cls/**/__tests__/*', ignore: true},
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      {pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false}
    ],

    tests: [
      'src-cls/**/__tests__/*.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    
    env: {
      type: 'node', runner: 'node'
    },
    
    testFramework: 'mocha',
    
    debug: true,
    setup: function () {
      require('babel-polyfill');
    }
  };
};
```

### webpack configuration file
```javascript
'use strict';
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const npmPackage = require('./package.json');
const host = '0.0.0.0';
const port = 3000;

const config = {
  entry: [
    'babel-polyfill',
    './src-cls/app'
  ],

  output: {
    path:       './dist-cls',
    publicPath: `http://${host}:${port}/`,
    filename:   'app.js'
  },
  
  resolve: {
    root: './src-cls',
    alias: {},
    extensions: ['', '.js', '.jsx'],
    modulesDirectories: npmPackage._moduleDirectories || []
  },
  
  module: {
    loaders: [
      {
        test:    /\.jsx?$/,
        loader: 'react-hot!babel?sourceMap&plugins[]=transform-runtime&presets[]=es2015,presets[]=stage-0,presets[]=react',
        exclude: /node_modules/
      },
      {
        test:    /\.css$/,
        loader:  'style!css?sourceMap!postcss',
        exclude: /node_modules/
      },
      {
        test:    /\.(png|jpg|gif|svg)$/,
        loader:  'url?limit=8192&name=images/[name].[ext]',
        exclude: /node_modules/
      },
      {
        test:    /\.(eot|ttf|woff|woff2)$/,
        loader:  'url?limit=8192&name=fonts/[name].[ext]',
        exclude: /node_modules/
      }
    ]
  },
  
  postcss: function (webpack) {
    return [
      require('postcss-import')({addDependencyTo: webpack, map: true}),
      require('postcss-url')(),
      require('postcss-cssnext')({map: true}),
      // require('postcss-browser-reporter')(),
      require('postcss-reporter')()
    ];
  },

  plugins: [
    new webpack.DefinePlugin({
      'process.env': {NODE_ENV: JSON.stringify('development')}
    }),
    new webpack.DefinePlugin({
      VERSION: JSON.stringify(npmPackage.version)
    }),
    new HtmlWebpackPlugin({
      template: 'src-cls/index.html',
      title: 'cls',
      inject: 'body'
    })
  ],

  devServer: {
    contentBase: './src-cls',
    cached:      false,
    colors:      true,
    port:        port,
    host:        host,
    noInfo:      false,
    quiet:       false,
    historyApiFallback: true,

    stats: {
      hash:    false,
      colors:  true,
      cached:  false,
      version: false,
      exclude: [
        // /node_modules\/(react|dev-server|core-js|react-router|babel-core|reflux|history)\//,
        // /webpack|babel-runtime/
      ]
    }
  }
};

module.exports = config;
```

### Code editor or IDE name and version

Atom v1.8.0

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
I think the issue is not related to the static properties, but happens because your JSX files are not compiled, because your compiler pattern only included `.js` files. Try changing the pattern to:
```javascript
compilers: {
      '**/*.js*': wallaby.compilers.babel()
    },
```
it should fix the issue.
BTW, you don't need these lines:
```
{pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
{pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false}
```
they are only required for browser environment testing, but you are using node environment (you seem to be using webpack though, but I'm assuming you can run your tests in node (without wallaby) - otherwise the config doesn't make sense because for browser tests in [webpack wallaby is configured differently](https://wallabyjs.com/docs/integration/webpack.html)).

If it doesn't address the issue, I have created the [repo with your files](https://github.com/wallabyjs/wallaby-647), it works for me, try to add the code to reproduce the issue there and let me know, I'll have a look.

**Comment by ArtemGovorov** [comment]
> ObiWan @ArtemGovorov , help this team get through this ordeal so we can buy our licenses and live a happy life full of tests.

May the Force be with you :)

**Comment by rpmonteiro** [comment]
Thank you very much for getting to me so quickly. That has indeed fixed *that* problem, but now 939 more have emerged! 
We have ```cannot find module ...``` errors in every single import statement except for node_modules packages. Any ideas? I've already read pretty much all the issues (open and closed) on the subject and still can't find the solution :(

**Comment by ArtemGovorov** [comment]
How does your command line for mocha (without wallaby) looks like?
Anyway, your wallaby config looks ok to me and I can't see anything wrong with it, so I'll need more context to be able to tell what's wrong. Please create a small sample repo demonstrating the issue and we'll take it from there.

**Comment by ArtemGovorov** [comment]
You may actually update the repo I [created for you](https://github.com/wallabyjs/wallaby-647) to demonstrate the issues you're having.

**Comment by rpmonteiro** [comment]
Doing it now! Thank you again Artem.

**Comment by ArtemGovorov** [comment]
Thanks for the PR, fixed the config: https://github.com/wallabyjs/wallaby-645/blob/master/wallaby.js
Things I changed:
- `tests` list [should only contain files with actual tests](https://wallabyjs.com/docs/config/files.html#tests),
- in the setup function registered `.jsx` extension so node can load it the same way as `.js` files,
- in the setup function required the same file you `require` in mocha.opts: `./src-cls/__tests__/setup.js`.

**Comment by rpmonteiro** [comment]
Perfect! We're one step closer.
Now we have a different kind of error, which is expected.
So, in the repo, we're importing files like '../../../../app/lalala.js' but in our project we've setup like an absolute path so we can now import the same file like 'lalala.js'. With the app folder being the 'root' of the imports. 

How to tell wallaby to do that as well?

**Comment by rpmonteiro** [comment]
To be a bit more clear, we sometimes import files from the root 'app' like 'components/lala.js' instead of '../../../../components/lala.js', and some other times we import it relative. So ideally wallaby will find everything

**Comment by ArtemGovorov** [comment]
How do you have it configured for mocha in your project? Should be pretty similar to configure for wallaby.

**Comment by ArtemGovorov** [comment]
If I understand it correctly, setting `NODE_PATH` to tell node where to look for your modules, should do the trick. I have [updated the repo to demonstrate it](https://github.com/wallabyjs/wallaby-645/commit/b0c19a77f840e529e3fe53cafcbaf0b9a2053e86).

**Comment by rpmonteiro** [comment]
Still doesn't work..
Check this image: http://bit.ly/1Q0GC35 directly from my atom view. Maybe it'll help explain.

Again, thank you very much for your help. We're really looking forward to integrate wallaby in our tools portfolio

**Comment by rpmonteiro** [comment]
Here's the current wallaby config 

```javascript
module.exports = function (wallaby) {

  process.env.NODE_PATH = require('path').join(wallaby.projectCacheDir, 'src-cls', 'app');
  
  return {
    files: [
      'src-cls/**/*.js*',
      {pattern: 'src-cls/**/__tests__/*-test.js', ignore: true},
      {pattern: 'src-cls/docs/*', ignore: true}

    ],

    tests: [
      'src-cls/**/__tests__/*-test.js'
    ],

    compilers: {
      '**/*.js*': wallaby.compilers.babel()
    },

    env: {
      type: 'node', runner: 'node'
    },

    testFramework: 'mocha',

    debug: true,
    setup: function () {
      require.extensions['.jsx'] = require.extensions['.js'];
      require('./src-cls/__tests__/setup');
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
Thanks for the screenshot. It looks like wallaby in your case for some reason is trying to resolve modules from your local project folder (and fails because they are obviously not compiled there), instead of resolving from the wallaby cache folder `wallaby.projectCacheDir` (where everything is instrumented). I can't yet see any reasons why. Could you please try changing the sample repo as before to reproduce the issue?

**Comment by ArtemGovorov** [comment]
I tried adding the file from screenshot into the repo, and it works for me: https://github.com/wallabyjs/wallaby-645/commit/35826a767b5d1713f3486f03c4667d5eca38f869. Perhaps something else in your setup is setting the `process.env.NODE_PATH`?

**Comment by rpmonteiro** [comment]
Actually, on the repo project, wallaby is stuck at ```tryModuleLoad```, just like in the actual project where we're trying to make it work!
Here's a screenshot:
https://www.dropbox.com/s/a7mqto4r5zwk8qd/Screenshot%202016-06-14%2014.09.06.png?dl=0

**Comment by rpmonteiro** [comment]
So, there are no errors occurring, but wallaby seems to be 'stuck', which is very weird! On your end with the exact same configs it works.

**Comment by ArtemGovorov** [comment]
Sorry, it was my fault, the latest core update was corrupted. [Force the core update like described here](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by ArtemGovorov** [comment]
Let me know once you force the core update and have a chance to try reproducing the issue in the sample repo.

**Comment by rpmonteiro** [comment]
Doing it now! ;-)

**Comment by rpmonteiro** [comment]
I can't reproduce the issue in the sample repo, even though I'm replicating the same folder structure. It works fine there.
On the project here's what happens: http://bit.ly/1tolZDn
Those lines that it tells me about are just some simple ```export default```. Any ideas?

Also, is there a way of making 'src-cls' a root path as well?
At the moment only app is: ``` wallaby.projectCacheDir, 'src-cls', 'app');```. 

Thank you again Artem

**Comment by ArtemGovorov** [comment]
My only idea is that something else in your setup/app is setting the `process.env.NODE_PATH`.

We may verify the assumption by checking the value right before executing tests. In your real app, try commenting `debug` flag (to reduce the logging noise), adding `console.log` for the `process.env.NODE_PATH` at the end of your `setup` function:

```javascript
module.exports = function (wallaby) {

  ...

  return {
    ...

    // debug: true,
    setup: function () {
      require.extensions['.jsx'] = require.extensions['.js'];
      require('./src-cls/__tests__/setup');

      console.log(process.env.NODE_PATH); // <--- should not contain your local project path, only wallaby cache path
    }
  };
};
```
Run the config and check the displayed value in Atom Dev Tools console.

> Also, is there a way of making 'src-cls' a root path as well?

Yes.

```javascript
var path = require('path');
process.env.NODE_PATH = path.join(wallaby.projectCacheDir, 'src-cls', 'app') 
  + path.delimiter
  + path.join(wallaby.projectCacheDir, 'src-cls');
```

I'm wondering, how do you configure plain mocha to do all these? You should be doing similar things somewhere in order to run your tests in plain mocha. Perhaps the `process.env.NODE_PATH` is overwritten when you do it?

**Comment by rpmonteiro** [comment]
I run the tests from:

#### package.json
```json
"test": "npm run test:cls",
"test:cls": "clear && watch 'npm run --silent mocha:cls' ./src-cls -d -u",
```

#### mocha.opts
```yaml
--compilers js:babel-register
--require ./src-cls/__tests__/setup.js
--reporter dot
```

So as you see, there's nothing special.
At the moment, wallaby is almost working for the entire project (around 80%). Your latest tip of adding another path worked great!

Here's the result from that console.log:
```
Wallaby Console: console.log: /Users/rpmonteiro/.atom/packages/atom-
wallaby/projects/7df419cb4941eeae/instrumented/src-cls/app:/
Users/rpmonteiro/.atom/packages/atom-wallaby/projects/
7df419cb4941eeae/instrumented/src-cls
```
Also looks fine, now with 2 paths added to it.

What's weird is that it's throwing 2 errors which are causing the tests not to run in all files that require them:
```
export function col2rgba(str, alpha) {  
Wallaby Console: ^^^^^^  
Wallaby Console: SyntaxError: Unexpected token export
```
and
```
import settings from '../config/settings';
Wallaby Console: ^^^^^^
Wallaby Console: SyntaxError: Unexpected token import
```

There's nothing special about them. They're included in the paths, syntax is just like all other files... and I think this is the last bit preventing wallaby from running all tests. Any ideas?

I'm including the logs in case it might help:
[-1465977031194.txt](https://github.com/wallabyjs/public/files/315643/-1465977031194.txt)

**Comment by ArtemGovorov** [comment]
Thanks, I think we are very close, but I'm out of ideas as to why the last 2 errors are happening. Especially puzzling is that you cannot reproduce them in the sample repo. Would it be possible to take your real project, copy it somewhere locally, delete most of it (all business sensitive stuff) and leave a couple of files where the issue is still reproduced? You may send it to me directly to hello@wallabyjs.com if you don't like to upload it here.

**Comment by rpmonteiro** [comment]
Thank you Artem, we'll do that. We just bought 2 licenses as you've been very helpful and we have no doubts this will be solved.

**Comment by ArtemGovorov** [comment]
> I run the tests from:
> ...
> So as you see, there's nothing special.

How does your plain mocha run know to load modules from `src-cls/app` and `src-cls` (so that you can import 'components/lala.js' instead of '../../../../components/lala.js')? It needs to do something similar somewhere. For example in [the sample repo](https://github.com/wallabyjs/wallaby-645) where wallaby currently runs ok because of setting the `process.env.NODE_PATH`, mocha fails with the ` Cannot find module` error. The reason I'd like to understand how mocha is able to do the same thing in your specific case is because it may be related to the last two issues we are observing.

**Comment by rpmonteiro** [comment]
Can this be the cause of it? It's called `module-alias` and its purpose is exactly to specify a directory as a module e.g `components/lala.js` instead of `../../../../../../components/lala.js`

I've added the exact same directories to wallaby's Node Env path

#### Package.json
https://www.dropbox.com/s/mx6kkg1tj23m797/Screenshot%202016-06-16%2008.59.11.png?dl=0

#### Wallaby.js
https://www.dropbox.com/s/78u8ufa91kxjg0m/Screenshot%202016-06-16%2008.59.37.png?dl=0

**Comment by ArtemGovorov** [comment]
I think it can very likely be the reason.
Try mocking out the module in wallaby config `setup` function (so that it does nothing):
```javascript
    ...
    setup: function () {
      require.cache[require.resolve('module-alias/register')] = {};
      ...
    }
```

**Comment by rpmonteiro** [comment]
Artem, that cancer of a package `module-alias` was breaking everything.

I've removed it, used another one called `babel-plugin-module-alias` and everything works perfectly now! 

Thank you so much for helping us getting through this. We're now happy wallaby users.

Have a nice day :)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
