### ISSUE TITLE
Show last run screenshot

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#73]
In the example video on the Wallaby homepage you see the "Show last run screenshot" command, which shows the web page with the calculator. When is the screenshot exactly taken?

The calculator element is added to the body and never removed from the body, but in most cases we want to clean up the DOM after each test, i.e. when using jasmine-jquery fixtures. This results in a blank screenshot.

It would be awesome if the context menu is `it`-dependent, so that the presented screenshot is the element state after running the `it`, before cleanup.
This gives more insight into the tests than a screenshot after the tests.

**Comment by ArtemGovorov** [comment]
Wallaby has some smarts to do exactly what you said.

For example, try editing one of your tests and after editing it, try using context 'Show last run screen shot'. You should be able to see the screenshot, even if you have some cleanup code. In the case when wallaby runs only one test, it takes the screenshot before executing any cleanup code (in any testing framework it supports).

Another scenario ([described here in docs for the 'Show last run screen shot'](https://github.com/wallabyjs/public#context-actions)) is when you don't want to edit your test, but want to run it and see the screenshot for it. You can do this by using 'Run scope test(s)' context action which will run just that one test for you and, because it is a single test run, wallaby will take the screenshot before executing any cleanup code. So using context 'Show last run screen shot' after that will display the desired screenshot.

Please let me know if you have some ideas how to make the feature better or what can be improved in terms of user experience.

**Comment by fvanwijk** [comment]
Ah right, the docs page is so long that I forgot to read until the end (perhaps split up into multiple pages?), because when everything was setup op correctly, it just started playing and forgot to read on. Sorry.

Anyhow, testing software without reading docs is a good measurement for usability ;).
For me it wasn't immediately clear what a scope is in "Run scope tests", especially when testing Angular apps, which have scopes all over the place ;). Jasmine uses the concept "focused test", hence **f**describe.

One thing that confuses me a little bit is that it is not always clear what tests are running, because there are automatic runned tests and manually runned tests.

When I start running Wallaby all tests are running automatically. When I change a line in my source code, the tests that are covering that line are running, right? Furthermore you can run tests manually via the context menu.
So what is, in terms of UX, the difference between running a test automatically by modifying your code, and running the test scope via the context menu?

In any case, the screenshot popup is blank in my project.

```
beforeAll(function () {
  var element = $compile($templateCache.get(template), $scope);
  jasmine.getFixtures().load(testTemplatePath); // contains div#container
  $(document.body).find('#container').append(element);
});
``` 

When I do not add the wrapping template, everything works. So it looks like the jasmine-jquery fixture is already removed before making the screenshot?

Note: I'm using a `beforeAll` because I want to reuse the compiled and linked element for performance reasons. Changing the `beforeAll` in `beforeEach` doesn't help.

**Comment by ArtemGovorov** [comment]
I agree, 'scope' sounds confusing. Maybe we should rename it to 'context'? 

Anyway, 'Run scope tests' currently means: 
- Run current test if the action is invoked while in the function scope of a single test
- Run all tests within a test file if the action is invoked while in a function scope of a test file, but the function is not a test, for example `beforeEach` or just somewhere in `describe` but not inside any `it`.
- Run all tests that cover a source file if the action is invoked while in a function scope of the source file.

You are correct, wallaby tries to run tests automatically whenever it can and only runs a minimal required set of tests affected by your code changes. It doesn't always mean only tests covering the line, there are quite a few additional heuristics, but yes, the idea is to run tests automatically whenever possible.

Manual actions exist to run arbitrary tests without having to modify them, for example to see latest screenshots for them. Manual actions also sometimes be helpful in cases where wallaby can't guess what tests to run (there're very few cases like that and I'm adding more heuristics to get rid of them).

Regarding the issue with screenshot, if you have some time, could you please provide a full sample that I could run to reproduce the issue?

**Comment by fvanwijk** [comment]
I created a minimal example in a [gist](https://gist.github.com/fvanwijk/2c53affd5e1751fef6cc) to show when the screenshot is blank.

**Comment by ArtemGovorov** [comment]
Thanks for the provided example! The issue is fixed, show be working now (just restart wallaby, it should update itself automatically).

**Comment by fvanwijk** [comment]
Hmm it is not updating automatically. Downloaded zip is v1.0.5 and version under IntelliJ Plugins is 1.0.7

**Comment by ArtemGovorov** [comment]
Core and plugin are updated (and versioned) separately, core is updated transparently (after wallaby.js restart), so you may have not noticed the update. Try if your sample now works for you:

![test](https://cloud.githubusercontent.com/assets/979966/7241958/aa9a8826-e801-11e4-97dd-e70134f1f52f.gif)

**Comment by fvanwijk** [comment]
Thanks for the fix.
I found one case, when this still doesn't work. Sorry for not including this case immediately.

Duplicate the `it`, run file tests and show the screenshot for the second `it`. Then the screen is still blank.

**Comment by ArtemGovorov** [comment]
Confirmed, wallaby doesn't work in this case because the test name is duplicated. Re-opening the issue.

**Comment by fvanwijk** [comment]
If you change the second test name to something unique, I see a blank screenshot either.

**Comment by ArtemGovorov** [comment]
Can't reproduce with the unique name, just with the duplicate. Do you invoke `Run scope test(s)` for the second (renamed uniquely) test before requesting the screenshot? Here is how it works for me (before and after renaming):
![test](https://cloud.githubusercontent.com/assets/979966/7269675/4e63a7ae-e919-11e4-853a-76197861bf09.gif)

**Comment by fvanwijk** [comment]
Yes with 'run scope tests' it works for both the first and the second `it`, but with 'run file test(s)`, I expect the screenshot to be visible too.

**Comment by ArtemGovorov** [comment]
When wallaby runs all tests in a file, either automatically or manually, it by design doesn't bother to intercept teardown code before making a screenshot. The reason is that most because your tests do teardown, the screenshot will only have some data from the last test that did run.

**Comment by fvanwijk** [comment]
The expected behaviour IMO is that when running all the tests, either automatically or manually, the screenshot is from the last test (in the file?), just before the teardown code runs.

From usability point of view I think that will be a improvement, since you can see the screenshot for the whole test suite with 1 command.

In any case, I expect to see the screenshot of the last test in the file to be visible when running only the file tests.

**Comment by DinisCruz** [comment]
For others who might also have the 'empty' screenshot,  my problem was that my test was not adding the element to the $document

```coffee
expect = chai.expect

describe '| directive | component | index', ->

  element     = null
  element_Raw = null
  scope       = null

  beforeEach ()->
    module('TM_App')

  beforeEach ()->
    inject ($compile,$rootScope)->
      element_Raw = angular.element('<results/>')
      element     = $compile(element_Raw)($rootScope.$new())[0]
      $rootScope.$digest()
      scope = element_Raw.find('div').eq(0).scope()             # getting the scope for the Controller

    inject ($document)->                                        # testing Wallaby screenshot
      body = angular.element $document[0].body
      body.append(element)
      #body[0].bgColor = 'white'
      body.append('<h1>Hello</h1>')
```

what is really cool is doing this together with a real-time image viewer (in the screenshot bellow I'm using Atom)

![image](https://cloud.githubusercontent.com/assets/656739/9151771/3d81c48c-3e07-11e5-956c-d09c30f4011a.png)

**Comment by ArtemGovorov** [comment]
@DinisCruz Nice idea and the workflow with real-time screenshot updating!

**Comment by DinisCruz** [comment]
yeah it really makes a big difference, here it is rending an Angular directive

![](https://slack-files.com/files-tmb/T040W512C-F08RJ56SF-86d90b854f/pasted_image_at_2015_08_09_11_13_pm_1024.png)

**Comment by smcenlly** [comment]
Closing this as stale/obsolete. This thread is from 2015 and no longer describes a current actionable bug report.
